# fly.toml app configuration file generated for urlshortener-kagami on 2023-08-11T19:53:35-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "urlshortener-kagami"
primary_region = "yyz"

[build]

[env]
  PORT=8080

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
